---
- name: set hostnamectl
  hostname:
    name: "{{ inventory_hostname }}"
  notify: restart_hostnamed

- meta: flush_handlers

- name: set timezone to UTC
  timezone:
    name: UTC

- name: set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
    state: present
    backup: true
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"
