---
- name: set hostnamectl
  hostname:
    name: "{{ inventory_hostname }}"
  notify: restart_hostnamed

- meta: flush_handlers

- name: set timezone to UTC
  timezone:
    name: UTC

- name: set hostname in /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: true

- name: install firewalld
  package:
    name: firewalld
    state: present

- name: configure firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: true
